-- 批量插入 50 个邮箱地址到 D1
INSERT OR IGNORE INTO addresses (address, label, notes) VALUES
('reg-01@neumabio.xyz', '通用注册', '批量注册邮箱 #1'),
('reg-02@neumabio.xyz', '通用注册', '批量注册邮箱 #2'),
('reg-03@neumabio.xyz', '通用注册', '批量注册邮箱 #3'),
('reg-04@neumabio.xyz', '通用注册', '批量注册邮箱 #4'),
('reg-05@neumabio.xyz', '通用注册', '批量注册邮箱 #5'),
('reg-06@neumabio.xyz', '通用注册', '批量注册邮箱 #6'),
('reg-07@neumabio.xyz', '通用注册', '批量注册邮箱 #7'),
('reg-08@neumabio.xyz', '通用注册', '批量注册邮箱 #8'),
('reg-09@neumabio.xyz', '通用注册', '批量注册邮箱 #9'),
('reg-10@neumabio.xyz', '通用注册', '批量注册邮箱 #10'),
('reg-11@neumabio.xyz', '通用注册', '批量注册邮箱 #11'),
('reg-12@neumabio.xyz', '通用注册', '批量注册邮箱 #12'),
('reg-13@neumabio.xyz', '通用注册', '批量注册邮箱 #13'),
('reg-14@neumabio.xyz', '通用注册', '批量注册邮箱 #14'),
('reg-15@neumabio.xyz', '通用注册', '批量注册邮箱 #15'),
('reg-16@neumabio.xyz', '通用注册', '批量注册邮箱 #16'),
('reg-17@neumabio.xyz', '通用注册', '批量注册邮箱 #17'),
('reg-18@neumabio.xyz', '通用注册', '批量注册邮箱 #18'),
('reg-19@neumabio.xyz', '通用注册', '批量注册邮箱 #19'),
('reg-20@neumabio.xyz', '通用注册', '批量注册邮箱 #20'),
('reg-21@neumabio.xyz', '通用注册', '批量注册邮箱 #21'),
('reg-22@neumabio.xyz', '通用注册', '批量注册邮箱 #22'),
('reg-23@neumabio.xyz', '通用注册', '批量注册邮箱 #23'),
('reg-24@neumabio.xyz', '通用注册', '批量注册邮箱 #24'),
('reg-25@neumabio.xyz', '通用注册', '批量注册邮箱 #25'),
('reg-26@neumabio.xyz', '通用注册', '批量注册邮箱 #26'),
('reg-27@neumabio.xyz', '通用注册', '批量注册邮箱 #27'),
('reg-28@neumabio.xyz', '通用注册', '批量注册邮箱 #28'),
('reg-29@neumabio.xyz', '通用注册', '批量注册邮箱 #29'),
('reg-30@neumabio.xyz', '通用注册', '批量注册邮箱 #30'),
('aws@neumabio.xyz', 'AWS', 'AWS 账号注册'),
('azure@neumabio.xyz', 'Azure', 'Microsoft Azure 账号'),
('gcp@neumabio.xyz', 'GCP', 'Google Cloud Platform'),
('do@neumabio.xyz', 'DigitalOcean', 'DigitalOcean VPS'),
('vultr@neumabio.xyz', 'Vultr', 'Vultr VPS'),
('linode@neumabio.xyz', 'Linode', 'Linode VPS'),
('hetzner@neumabio.xyz', 'Hetzner', 'Hetzner Cloud'),
('cloudflare@neumabio.xyz', 'Cloudflare', 'Cloudflare 账号'),
('vercel@neumabio.xyz', 'Vercel', 'Vercel 部署'),
('netlify@neumabio.xyz', 'Netlify', 'Netlify 部署'),
('github@neumabio.xyz', 'GitHub', 'GitHub 账号'),
('gitlab@neumabio.xyz', 'GitLab', 'GitLab 账号'),
('docker@neumabio.xyz', 'Docker', 'Docker Hub'),
('npm@neumabio.xyz', 'NPM', 'npm 注册'),
('openai@neumabio.xyz', 'OpenAI', 'OpenAI API'),
('anthropic@neumabio.xyz', 'Anthropic', 'Claude API'),
('googleai@neumabio.xyz', 'Google AI', 'Gemini API'),
('notify@neumabio.xyz', '通知', '系统通知'),
('test@neumabio.xyz', '测试', '测试邮箱'),
('admin@neumabio.xyz', '管理员', 'Admin mailbox');
